#!/bin/bash
set -e

# Update system
sudo yum update -y

# Install required tools
sudo yum install -y wget git

# Install Java 17 (required)
sudo yum install -y java-17-amazon-corretto

# Install Maven
sudo yum install -y maven

# Verify installations
java -version
mvn -version

# Add Jenkins repo
sudo wget -O /etc/yum.repos.d/jenkins.repo \
https://pkg.jenkins.io/redhat-stable/jenkins.repo

# Import Jenkins GPG key
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

# Install Jenkins
sudo yum install -y jenkins

# Start Jenkins
sudo systemctl daemon-reload
sudo systemctl start jenkins
sudo systemctl enable jenkins
